import type { Metadata } from 'next'
import React from 'react'
import { NextIntlClientProvider, useMessages } from 'next-intl'
import StyledComponentsRegistry from '@/lib/registry'
import { GlobalStyleProvider } from '@/lib/globalStyleProvider'
import * as S from '@/lib/responsiveStyle'
import Header from '@/lib/components/header'
import Footer from '@/lib/components/footer'

export const metadata: Metadata = {
  title: 'Next.js 14 TEST',
  description: 'Generated by create next app',
}

export default function LocaleLayout({ children, params: { locale } }: { children: React.ReactNode; params: { locale: string } }) {
  const messages = useMessages()

  return (
    <NextIntlClientProvider locale={locale} messages={messages} timeZone="Asia/Seoul">
      <StyledComponentsRegistry>
        <GlobalStyleProvider>
          <html lang={locale}>
            <body>
              <S.ResponsiveStyle>
                <Header />
                <main>{children}</main>
                <Footer />
              </S.ResponsiveStyle>
            </body>
          </html>
        </GlobalStyleProvider>
      </StyledComponentsRegistry>
    </NextIntlClientProvider>
  )
}
