import type { Metadata } from 'next'
import { NextIntlClientProvider, useMessages } from 'next-intl'
import React from 'react'
import StyledComponentsRegistry from '@/lib/registry'
import { GlobalStyles } from '@/lib/globalStyles'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function LocaleLayout({ children, params: { locale } }: { children: React.ReactNode; params: { locale: string } }) {
  const messages = useMessages()

  return (
    <NextIntlClientProvider locale={locale} messages={messages} timeZone="Asia/Seoul">
      <StyledComponentsRegistry>
        <GlobalStyles />
        <html lang={locale}>
          <body>
            {/* children */}
            {children}

            {/* Side Menu */}
            <div>Side Menu</div>
          </body>
        </html>
      </StyledComponentsRegistry>
    </NextIntlClientProvider>
  )
}
