import type { Metadata } from 'next'
import React from 'react'
import { NextIntlClientProvider, useMessages } from 'next-intl'
import StyledComponentsRegistry from '@/lib/registry'
import { GlobalStyleProvider } from '@/lib/globalStyleProvider'
import ThemeProvider from '@/lib/themeProvider'
import { darkTheme } from '@/lib/theme/darkTheme'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function LocaleLayout({ children, params: { locale } }: { children: React.ReactNode; params: { locale: string } }) {
  const messages = useMessages()

  return (
    <NextIntlClientProvider locale={locale} messages={messages} timeZone="Asia/Seoul">
      <StyledComponentsRegistry>
        <ThemeProvider>
          <GlobalStyleProvider>
            <html lang={locale}>
              <body>
                {/* children */}
                {children}

                {/* Side Menu */}
                <div>Side Menu</div>
              </body>
            </html>
          </GlobalStyleProvider>
        </ThemeProvider>
      </StyledComponentsRegistry>
    </NextIntlClientProvider>
  )
}
